# Generated by Django 4.1.2 on 2022-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('ch_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(default='', max_length=70)),
                ('companyname', models.CharField(max_length=85)),
                ('country', models.CharField(max_length=45)),
                ('town', models.CharField(max_length=157)),
                ('state', models.CharField(max_length=15)),
            ],
        ),
    ]
