# Generated by Django 4.1.2 on 2022-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='companyname',
            field=models.CharField(default='', max_length=85),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='firstname',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='lastname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.PositiveIntegerField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='town',
            field=models.CharField(default='', max_length=157),
        ),
    ]
